name: gpath
channels:
- insilichem
- omnia
- bioconda
dependencies:
- python=2.7
- nomkl
- openmm
- openmoltools
- pdbfixer
- cclib
- numpy
- git
- smina
- pip:
  - pychimera
  - munch
  - voluptuous
  - click
  - boltons
  - deap
  - pyyaml
  - prody==1.8.2

